Fix all hanging paragraphs.
SMPTE/standards-operations-manual pull request #43
Opened 2022-12-15 02:03 UTC by dcbullock

- add sub-sections where needed
 - reflow

2022-12-15 02:05 UTC, dcbullock commented
Should we enable all CI for this branch and keep adding fixes until it passes?

2022-12-15 22:54 UTC, palemieux requested changes
Incorrect heading levels, e,g.:

https://github.com/SMPTE/standards-operations-manual/blob/db79d6383fe4f6e44a925f19cc1db5cc030fb74f/doc/main.html#L609

2022-12-20 17:47 UTC, fschleich requested changes
quick demo of the redlining system

2022-12-20 17:47 UTC, fschleich commented on doc/main.html
> +          <h4>Introduction</h4>
this should be "Overview"
```suggestion
          <h4>Overview</h4>
```

2022-12-20 17:47 UTC, fschleich commented on doc/main.html
> +              <h6>Introduction</h6>
this should be "Overview"
```suggestion
              <h6>Overview</h6>
```

2025-02-25 17:06 UTC, fschleich commented
Superseeded by https://github.com/SMPTE/standards-operations-manual/pull/46

2025-02-25 17:06 UTC, closed without merging